/*
 * Listas extraídas das tabelas conectadas do formulário de origem no Pipefy
 * (Triagem de Saúde Ocupacional — SBM OFFSHORE). São nomes próprios: valem
 * igual em português e inglês, por isso não passam pelo dicionário.
 */

/** Tabela "DB - BR NET (SBM OFFSHORE)" — campo 4, unidade de embarque. */
export const UNITS = [
  "FPSO ALEXANDRE GUSMÃO (SBM - OPERAÇÕES ESPECIAIS)",
  "FPSO CIDADE DE MARICÁ",
  "FPSO CIDADE DE SAQUAREMA",
  "FPSO CIDADE DE PARATY",
  "FPSO ESPÍRITO SANTO",
  "FPSO SEPETIBA",
  "FPSO CIDADE DE ANCHIETA",
  "FPSO CIDADE DE ILHABELA",
  "FPSO CAPIXABA",
] as const;

/** Tabela "Empresas Terceirizadas - SBM OFFSHORE" — campo 5.1. */
export const CONTRACTORS = [
  "AMBIENTEC CONSULTORIA SEG E HIG DO TRAB LTDA",
  "AMBIPAR RESPONSE TANK CLEANING S/A",
  "AMERICAN BUREAU OF SHIPPING",
  "APPLUS K2",
  "ARAUJO ENGENHARIA E INTEGRIDADE DE EQUIP IND LTDA",
  "ARM ARMAZENS GERAIS E LOGISTICA LTDA",
  "ATLAS PROFESSIONALS DO BRASIL LTDA",
  "AVANTIS BRASIL LTDA",
  "AXESS DO BRASIL LTDA",
  "BAHIA CONTROL COM REPRESENTACOES E SERV LTDA",
  "BAKER HUGHES ENERGY TECHNOLOGY DO BRASIL LIMITADA",
  "CME COMERCIO DE MAQUINAS E EQUIPAMENTOS LTDA",
  "CONBIT",
  "CONSTRUTORA BARRA DO SANA LTDA COBASA",
  "EMERSON PROCESS MANAGEMENT LTDA",
  "EMPRESA CONSTRUTORA BRASIL SA",
  "FRATELLI COSULICH COMERCIO E SERVICOS LTDA",
  "GRANIHC SERVICES SA",
  "GT QUIMICA SOLUCOES ANALISES LABORATORIA",
  "GUARAPARI EXTINTORES LTDA ME",
  "H TECH SERVICOS E MANUTENCAO LTDA ME",
  "HANSA-FLEX DO BRASIL LTDA",
  "HARRIS PYE BRASIL LTDA",
  "HIGH QUALITY GESTAO EM PROGRAMAS DE QUALIDADE LTDA",
  "HITA COMERCIO E SERVICOS LTDA",
  "IKM TESTING BRASIL LTDA",
  "INTERNATIONAL PERSONAL SERVICE",
  "JABARRA SERVICOS DE RADIOPROTECAO LTDA ME",
  "LESER VALVULAS DE SEGURANÇA LTDA",
  "LIFTING ASSISTENCIA TECNICA ELETRICA E COMERCIAL LTDA",
  "LUBRIN LUBRIFICACAO INDUSTRI EIRELI",
  "M7 SOLUCOES OFFSHORE LTDA",
  "MANSERV MONTAGEM E MANUTENCAO SA",
  "MDE BRASIL RECRUTAMENTO ESPECIALIZADO LTDA",
  "METROVAL CONTROLES DE FLUIDOS LTDA",
  "OCEANICA ENGENHARIA E CONSULTORIA SA",
  "OCYAN S.A",
  "PENSALAB EQUIPAMENTOS INDUSTRIAIS S/A",
  "PLIMSSOL (AMBIPAR) RESPONDE INDUSTRIAL SERVICES",
  "PRINER SERVICOS INDUSTRIAIS SA",
  "QUALITECH INSPECAO REPARO E MANUTENCAO",
  "RADIX ENGENHARIA E DESENVOLVIMENTO DE SOFTWARE SA",
  "SERVICOS MARITIMOS CONTINENTAL SA",
  "SIEMENS ENERGY BRASIL LTDA",
  "SMARTCOAT SERVICOS EM REVESTIMENTOS SA",
  "SODEXO DO BRASIL COMERCIAL SA",
  "SPARROWS BSM ENGENHARIA LTDA",
  "STEP OIL E GAS SERVICOS LTDA",
  "SULZER BRASIL SA",
  "SUPPLY MARINE SERVICOS LTDA",
  "TECNOFINK LTDA.",
  "TERRA DRONE BRASIL SERVICOS DE ENGENHARIA LTDA",
  "V SHIPS BRASIL OFFSHORE SA",
  "VERTICAL UP OFFSHORE LTDA",
  "WEG EQUIPAMENTOS ELETRICOS SA",
  "WOOD GROUP ENG AND PROD FACILITIES BRASIL LTDA",
  "ZARPA CREW SERVICOS MARITIMOS LTDA",
  "ZERUST PREVENCAO DE CORROSAO LTDA",
] as const;

/** Tabela "Funções - SBM OFFSHORE" — campo 6. */
export const POSITIONS = [
  "Ajudante",
  "Ajudante de Cozinha",
  "Almoxarifado",
  "Almoxarife",
  "Alpinista de Resgate",
  "Alpinista Industrial",
  "Alpinista Industrial II",
  "Analista de Sistemas",
  "Arrumador",
  "Assistente Técnico",
  "Auxiliar de Almoxarifado",
  "Auxiliar de Cozinha",
  "Auxiliar de Inspeção",
  "Auxiliar de Limpeza",
  "Auxiliar de Operação",
  "Auxiliar de Operações",
  "Auxiliar de Segurança",
  "Auxiliar Operacional",
  "Caldeireiro",
  "Caldeireiro Alpinista",
  "Camareiro",
  "Chef de Cozinha",
  "Chef Executivo",
  "Comandante de Cabotagem",
  "Comandante de Manobra",
  "Comissionador",
  "Coordenador",
  "Coordenador de Automação",
  "Coordenador de Materiais",
  "Coordenador Operacional",
  "Coordenador Técnico de Segurança",
  "Cozinheiro",
  "Eletricista",
  "Eletricista Alpinista Nível 3",
  "Eletrotécnico",
  "Encarregado",
  "Encarregado de Construção",
  "Encarregado de Convés",
  "Enfermeiro(a)",
  "Engenheiro",
  "Engenheiro de Campo",
  "Engenheiro de Equipamentos Rotativos",
  "Engenheiro de ICSS (Sistema Integrado de Controle e Segurança)",
  "Engenheiro de Lubrificação",
  "Engenheiro de Manutenção",
  "Engenheiro de Serviços",
  "Engenheiro Eletrônico",
  "Engenheiro Supervisor",
  "Especialista de Campo",
  "Gerente",
  "Gerente de Andaimes",
  "Gerente de Instalação Offshore (OIM)",
  "Gerente de Montagem",
  "Gerente de Operações",
  "Gerente de Serviços",
  "Governança",
  "Inspetor",
  "Inspetor Alpinista",
  "Inspetor de Área Classificada (Ex)",
  "Inspetor de Contrato",
  "Inspetor de Ensaios Não Destrutivos (END)",
  "Inspetor de Equipamentos",
  "Inspetor de Integridade",
  "Inspetor de Integridade III",
  "Inspetor de Pintura",
  "Inspetor de Qualidade",
  "Instrumentação",
  "Instrumentista",
  "Laboratório",
  "Líder de Processo",
  "Líder Elétrico",
  "Lubrificador",
  "Manutenção",
  "Marinheiro",
  "Marinheiro de Convés",
  "Mecânico",
  "Mecânico Alpinista",
  "Mergulhador",
  "Mergulhador Autônomo",
  "Montador",
  "Montador de Andaimes",
  "Montador Industrial",
  "Nutricionista",
  "Oceanógrafo",
  "Oficial de Cozinha",
  "Oficial de Manutenção",
  "Oficial de Preservação",
  "Oficial de Segurança",
  "Operacional",
  "Operacional Júnior",
  "Operador",
  "Operador de Ar",
  "Operador de Bombas",
  "Operador de Carga",
  "Operador de Convés",
  "Operador de Guindaste",
  "Operador de Hidrojateamento",
  "Operador de Manutenção",
  "Operador de Máquina",
  "Operador de Nitrogênio",
  "Operador de Posicionamento Dinâmico (DPO)",
  "Operador de Produção",
  "Operador de Rádio",
  "Operador de Sala de Controle",
  "Operador de Serviços",
  "Operador Líder",
  "Padeiro",
  "Paioleiro",
  "Piloto de ROV",
  "Pintor",
  "Pintor Alpinista",
  "Pintor de Acesso por Corda",
  "Pintor de Hidrojateamento",
  "Químico",
  "Rigger",
  "Rigger N3",
  "Segurança",
  "Soldador",
  "Superintendente",
  "Superintendente de Carga",
  "Superintendente de Manutenção",
  "Superintendente de Mecânica",
  "Superintendente de Produção",
  "Supervisor",
  "Supervisor de Acesso",
  "Supervisor de Almoxarifado",
  "Supervisor de Alpinismo Industrial",
  "Supervisor de Andaimes",
  "Supervisor de Carga",
  "Supervisor de Construção",
  "Supervisor de Instrumentação",
  "Supervisor de Integridade",
  "Supervisor de Manutenção",
  "Supervisor de Mecânica",
  "Supervisor de Mergulho",
  "Supervisor de Movimentação de Carga",
  "Supervisor de Operações",
  "Supervisor de Produção",
  "Supervisor de Segurança do Trabalho",
  "Supervisor de Tubulação",
  "Supervisor Eletricista",
  "Supervisor Elétrico",
  "Supervisor N3",
  "Supervisor Técnico",
  "Taifeiro",
  "Técnico",
  "Técnico de Automação",
  "Técnico de Calibração",
  "Técnico de Campo",
  "Técnico de Controle de Pragas",
  "Técnico de Instrumentação",
  "Técnico de Laboratório",
  "Técnico de Lubrificação",
  "Técnico de Manutenção",
  "Técnico de Mecânica",
  "Técnico de Medição",
  "Técnico de Operações Júnior",
  "Técnico de Operações Júnior II",
  "Técnico de Produção",
  "Técnico de Refrigeração",
  "Técnico de Segurança",
  "Técnico de Segurança do Trabalho",
  "Técnico de Segurança Patrimonial",
  "Técnico de Telecomunicações",
  "Técnico Eletricista",
  "Técnico Eletrônico",
  "Técnico em Eletricidade",
  "Técnico Mecânico",
  "Técnico Operador",
  "Técnico Químico",
  "Técnico Trainee",
  "Tecnólogo em Elétrica",
  "Trainee de Produção",
  "Trainee Offshore",
  "Vistoriador",
] as const;

/** Campo 3: hoje o formulário de origem oferece uma única empresa. */
export const BOARDING_COMPANIES = ["SBM OFFSHORE"] as const;
